---
title: "Male......Voters Prefer to Vote for Conservative"
author: "Group 9 - Yijie Zhao, Yuze Kang, Shuyu Duan & Rachel Oh"
bibliography: "references.bib"
date: "October 7, 2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

# *Executive Summary*

1) the task (including specifying the client and the focus);
2) what was done;
3) what was found;
4) why this matters;
5) some weaknesses; and
6) areas for future work.


# *Introduction*

In Canadian federal election, Ontario has always been an important battleground. As the most populous province of Canada, Ontario counts 121 federal electoral districts (i.e., ridings in Canadian English) holding voting rights and has 121 seats, more than one third in the House of Commons. Therefore, polling of Ontario voters has a strategic significance for all ambiguous political parties, especially for Conservative. However, does it definitely lead Conservative to winning federal government by leading the poll before federal election? Absolutely not. Even a higher voting rate can not ensure a final winning, as a fact shows in 2019 Canadian federal election that Conservative lost government while gained more votes than Liberal. So both votes and seats matter. 

There is a variety of interior or exterior factors that affects each voter's decision on the election date and causes the consequence that polling is not as much reliable as we think. In the following context, we decide to focus on some common factors of voters themselves, such as age, sex, education and income level, to find the relation to their preferences of political parties. In addition to polling updates in October, we try to figure out if there is any common features of voters who prefer to vote Conservative in the federal election, for Conservative Party's reference. Based on that, no matter the voters are rational or irrational on that big date, we might use this observation to help Conservative stabilize their current voters and win over more voters of Ontario, to win more seats in such an important province. Besides, we discuss the weakness and limitation contained in our whole analyzing process for readers' reference and for improvement next time.

All the code and data supporting this analysis is available at: https://github.com/JessieZ32/Polling-for-Conservative.


# *Survey Methodology*

To achieve the aims of our report, we need to collect data first. Our target population is all the eligible voters of Ontario, i.e., any at least 18-year-old Canadian citizen without deprived of civil right whose residential address is located in Ontario. And our sampling population is whom we can possibly reach out among the target population. For data collection, we first designed an appropriate anonymous survey for voters of Ontario, including all information, or say, variables we are interested in, through SurveyMonkey. The link and a screenshot of our survey is available at the appendix of this report. 

We collaborated with some big Canadian communications and media companies, Rogers, Bell and Telus, as they own lists of customers' email addresses which may cover most of our target population (i.e., our frame). Through their email system, we massively sent emails with our survey URL link in. Both in content of email and survey, we promised to keep all the collected data residential, with respect to the protection of participants' privacy, and asked for ignorance if people who received this email weren't not eligible voters. Then we collected all the data from respondents as samples. Through the whole process, the sampling method that we used is simple random sampling without replacement (SRSWOR). We hope sample can be chosen with an equal probability, making the collected sample could represent target population with as less bias as possible. 

As for the costs of sampling process, we only need to calculate the wage we pay for employees who did the job of sending emails. Doing a survey through some kind of modern media can cost less that survey face-to-face. However, there exists some errors due to our sampling design. For example, delivering the survey to voters online can definitely cause non-response error. There is no way to ensure them checking email regularly and doing survey willingly. But we can increase the rate of response by setting up some rewards, for example, we can set a raffle page and all the respondents shall do a lucky raffle once they submit the survey. Hence, we can reduce the influence of non-response error as much as possible.


# *Results*




# *Discussion*

## simulation



# *Appendices*

survey screenshot @XXX


# *reference*



